<?php

function cp_helper_form_mailchimp_signup_subscribe_block_signup_form_alter(&$form, &$form_state, $form_id) {

	// Some pages modified differently
	/* Contact Pages. Thought I'd something more to say */
	if ('contact' == substr($form['#action'],-7)) {
		/* Not Contact Pages */
	} else {


	$form['mergevars']['FNAME']['#attributes'] = array(
 		'placeholder'=> t('first name'),
	);
		$form['mergevars']['LNAME']['#attributes'] = array(
 		'placeholder'=> t('last name'),
	);
		$form['submit']['#weight'] = -50;
	 	$form['mergevars']['FNAME']['#attributes']['weight'] = -20;
		$form['mergevars']['EMAIL']['#attributes']['weight'] = -99;
		$form['mergevars']['EMAIL']['#attributes']['placeholder'] = t('email address *');
	}
}
